import { Component, signal, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { LucideAngularModule, ArrowLeft, Save, X, ChevronDown, ChevronUp, Trash2, MoreVertical, Power, PowerOff } from 'lucide-angular';
import { MediaGalleryComponent, GalleryImage } from './media-gallery.component';
import { VariantManagerComponent } from './variant-manager.component';
import { TreeSelectComponent } from './tree-select.component';
import { TabBarComponent, type TabItem } from '../../shared/components/tab-bar/tab-bar.component';
import { FormFieldComponent } from '../../shared/components/form-field/form-field.component';
import { ButtonComponent } from '../../shared/components/button/button.component';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';
import { ProductService } from '../../services/product.service';
import { CategoryService } from '../../services/category.service';
import { Category } from '../../models/category.model';
import { ConfirmDialogService } from '../../shared/components/confirm-dialog/confirm-dialog.service';
import { ToastService } from '../../services/toast.service';
import { FileUploadService } from '../../services/file-upload.service';
import { firstValueFrom } from 'rxjs';

type TabId = 'basicas' | 'preco' | 'dimensoes' | 'variacoes';

interface Tab {
  id: TabId;
  label: string;
}

const TABS: Tab[] = [
  { id: 'basicas', label: 'Informações Básicas' },
  { id: 'preco', label: 'Preço e Custos' },
  { id: 'dimensoes', label: 'Dimensões' },
  { id: 'variacoes', label: 'Variações' },
];

@Component({
  selector: 'app-product-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, LucideAngularModule, MediaGalleryComponent, VariantManagerComponent, TreeSelectComponent, TabBarComponent, FormFieldComponent, ButtonComponent, PageHeaderComponent],
  templateUrl: './product-form.component.html',
  styleUrl: './product-form.component.scss',
})
export class ProductFormComponent {
  private readonly productService = inject(ProductService);
  private readonly categoryService = inject(CategoryService);
  private readonly confirmDialog = inject(ConfirmDialogService);
  private readonly toast = inject(ToastService);
  private readonly fileUploadService = inject(FileUploadService);

  readonly arrowLeftIcon = ArrowLeft;
  readonly saveIcon = Save;
  readonly closeIcon = X;
  readonly chevronDownIcon = ChevronDown;
  readonly chevronUpIcon = ChevronUp;
  readonly trashIcon = Trash2;
  readonly moreIcon = MoreVertical;
  readonly powerIcon = Power;
  readonly powerOffIcon = PowerOff;

  menuOpen = signal(false);

  readonly tabs = TABS;

  readonly tabItems: TabItem[] = TABS.map(t => ({ key: t.id, label: t.label }));

  activeTab = signal<TabId>('basicas');
  isEditMode = signal(false);
  productName = signal('');
  productId = signal('');
  loading = signal(false);
  isActive = signal(true);
  categoryTree = signal<Category[]>([]);
  skuAutoGenerated = signal(false);

  galleryImages = signal<GalleryImage[]>([]);
  galleryVideoUrl = signal<string | null>(null);

  // Mobile accordion: track which tabs are open
  openAccordions = signal<Set<TabId>>(new Set(['basicas']));

  form: FormGroup;

  margemEstimada = computed(() => {
    const preco = this.form?.get('precoVenda')?.value || 0;
    const custoAquisicao = this.form?.get('custoAquisicao')?.value || 0;

    if (preco <= 0) return null;

    return ((preco - custoAquisicao) / preco) * 100;
  });

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
  ) {
    this.form = this.fb.group({
      sku: [''],
      titulo: ['', [Validators.required, Validators.maxLength(60)]],
      descricao: [''],
      categoria: ['', [Validators.required]],
      fornecedor: [''],
      precoVenda: [null as number | null, [Validators.required, Validators.min(0.01)]],
      custoAquisicao: [null as number | null, [Validators.min(0)]],
      peso: [null as number | null],
      altura: [null as number | null],
      largura: [null as number | null],
      comprimento: [null as number | null],
    });

    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode.set(true);
      this.productId.set(id);
    }

    // Load categories first, then product (so TreeSelect can show the selection)
    this.loadCategories().then(() => {
      if (id) this.loadProduct(id);
    });
  }

  private async loadCategories(): Promise<void> {
    try {
      const tree = await this.categoryService.getTree();
      this.categoryTree.set(tree);
    } catch {
      // Silent fail — categories will be empty
    }
  }

  get titulo() { return this.form.get('titulo')!; }
  get categoria() { return this.form.get('categoria')!; }
  get precoVenda() { return this.form.get('precoVenda')!; }

  tituloLength(): number {
    return (this.form.get('titulo')?.value || '').length;
  }

  private async loadProduct(id: string): Promise<void> {
    this.loading.set(true);
    try {
      const product = await this.productService.getById(id);
      this.productName.set(product.name);
      this.isActive.set(product.isActive ?? true);
      this.form.patchValue({
        sku: product.sku,
        titulo: product.name,
        descricao: product.description ?? '',
        categoria: product.categoryId ?? '',
        fornecedor: product.supplier ?? '',
        precoVenda: product.price,
        custoAquisicao: product.acquisitionCost,
        peso: product.weight,
        altura: product.height,
        largura: product.width,
        comprimento: product.length,
      });

      // Load existing product images
      try {
        const files = await firstValueFrom(this.fileUploadService.getFiles('product', id));
        this.galleryImages.set(files.map((f, i) => ({
          id: f.id,
          url: f.url,
          fileName: f.fileName,
          order: f.sortOrder,
        })));
      } catch {
        // Images failed to load — non-critical
      }
    } catch {
      // Product not found or API error — stay on form with empty values
    } finally {
      this.loading.set(false);
    }
  }

  setActiveTab(tabId: TabId | string): void {
    this.activeTab.set(tabId as TabId);
  }

  toggleAccordion(tabId: TabId): void {
    const current = new Set(this.openAccordions());
    if (current.has(tabId)) {
      current.delete(tabId);
    } else {
      current.add(tabId);
    }
    this.openAccordions.set(current);
  }

  isAccordionOpen(tabId: TabId): boolean {
    return this.openAccordions().has(tabId);
  }

  async onCategoryChange(categoryId: string): Promise<void> {
    this.form.patchValue({ categoria: categoryId });
    this.form.get('categoria')?.markAsTouched();

    // Auto-suggest SKU if field is empty or was previously auto-generated
    const currentSku = this.form.get('sku')?.value || '';
    if (!currentSku || this.skuAutoGenerated()) {
      await this.suggestSku(categoryId);
    }
  }

  private async suggestSku(categoryId: string): Promise<void> {
    try {
      const suggested = await this.productService.getNextSku(categoryId);
      if (suggested) {
        this.form.patchValue({ sku: suggested });
        this.skuAutoGenerated.set(true);
      }
    } catch {
      // Silent fail — user can still type SKU manually
    }
  }

  async onSuggestSku(): Promise<void> {
    const categoryId = this.form.get('categoria')?.value;
    if (categoryId) {
      await this.suggestSku(categoryId);
    }
  }

  async toggleActive(): Promise<void> {
    const currentlyActive = this.isActive();
    const action = currentlyActive ? 'desativar' : 'ativar';
    const confirmed = await this.confirmDialog.confirm({
      title: `${currentlyActive ? 'Desativar' : 'Ativar'} Produto`,
      message: `Tem certeza que deseja ${action} o produto "${this.productName()}"?`,
      confirmLabel: currentlyActive ? 'Desativar' : 'Ativar',
      variant: currentlyActive ? 'warning' : 'primary',
    });

    if (!confirmed) return;

    try {
      await this.productService.update(this.productId(), {
        isActive: !currentlyActive,
      });
      this.isActive.set(!currentlyActive);
      this.confirmDialog.done();
      this.toast.show(
        `Produto ${!currentlyActive ? 'ativado' : 'desativado'} com sucesso`,
        'success',
      );
    } catch {
      this.confirmDialog.done();
      this.toast.show('Erro ao alterar status do produto', 'danger');
    }
  }

  async deleteProduct(): Promise<void> {
    const confirmed = await this.confirmDialog.confirm({
      title: 'Excluir Produto',
      message: `Tem certeza que deseja excluir o produto "${this.productName()}"?`,
      confirmLabel: 'Excluir',
      variant: 'danger',
    });

    if (!confirmed) return;

    try {
      await this.productService.delete(this.productId());
      this.confirmDialog.done();
      this.toast.show('Produto excluído com sucesso', 'success');
      this.router.navigate(['/produtos']);
    } catch {
      this.confirmDialog.done();
      this.toast.show('Erro ao excluir produto', 'danger');
    }
  }

  getMargemColor(): string {
    const margem = this.margemEstimada();
    if (margem === null) return 'var(--neutral-500)';
    if (margem >= 20) return 'var(--success)';
    if (margem >= 10) return 'var(--warning)';
    return 'var(--danger)';
  }

  onGalleryImagesChange(images: GalleryImage[]): void {
    this.galleryImages.set(images);
  }

  onGalleryVideoChange(url: string | null): void {
    this.galleryVideoUrl.set(url);
  }

  onCancel(): void {
    if (this.form.dirty && !confirm('Você tem alterações não salvas. Deseja sair?')) {
      return;
    }
    this.router.navigate(['/produtos']);
  }

  async onSave(): Promise<void> {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      // Switch to tab with first error and show feedback
      const invalidFields = Object.keys(this.form.controls).filter(k => this.form.get(k)?.invalid);
      console.warn('Form invalid. Fields:', invalidFields);
      if (this.titulo.invalid || this.categoria.invalid) {
        this.activeTab.set('basicas');
      } else if (this.precoVenda.invalid) {
        this.activeTab.set('preco');
      }
      this.toast.show('Preencha os campos obrigatórios destacados', 'warning');
      return;
    }

    this.loading.set(true);
    try {
      const formValue = this.form.value;
      const dto = {
        name: formValue.titulo,
        sku: formValue.sku || undefined,
        description: formValue.descricao || undefined,
        categoryId: formValue.categoria || undefined,
        supplier: formValue.fornecedor || undefined,
        price: formValue.precoVenda,
        purchaseCost: formValue.custoAquisicao ?? 0,
        packagingCost: 0,
        weight: formValue.peso ?? undefined,
        height: formValue.altura ?? undefined,
        width: formValue.largura ?? undefined,
        length: formValue.comprimento ?? undefined,
      };

      let productId: string;
      if (this.isEditMode()) {
        await this.productService.update(this.productId(), dto);
        productId = this.productId();
      } else {
        const created = await this.productService.create(dto);
        productId = created.id;
      }

      this.form.markAsPristine();
      this.toast.show('Produto salvo com sucesso', 'success');
      this.router.navigate(['/produtos', productId]);
    } catch {
      this.toast.show('Erro ao salvar produto', 'danger');
    } finally {
      this.loading.set(false);
    }
  }

  canDeactivate(): boolean {
    if (!this.form.dirty) return true;
    return confirm('Você tem alterações não salvas. Deseja sair?');
  }
}
